debug: false
listen: localhost:9000

postgres:
  host: localhost
  database: cantonres
  user: kevin
  password: foobar
  ssl: false

redis:
  addr: localhost:6379
  password: foobar
  database:
  prefix:

google:
  client_id:
  client_secret:
  map_key:
